import { pgTable, text, boolean, timestamp, integer } from 'drizzle-orm/pg-core'

export const user = pgTable('user', { id: text('id').primaryKey(), name: text('name').notNull(), email: text('email').notNull().unique(), emailVerified: boolean('emailVerified').notNull().default(false), image: text('image'), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const session = pgTable('session', { id: text('id').primaryKey(), expiresAt: timestamp('expiresAt').notNull(), token: text('token').notNull().unique(), createdAt: timestamp('createdAt').notNull(), updatedAt: timestamp('updatedAt').notNull(), ipAddress: text('ipAddress'), userAgent: text('userAgent'), userId: text('userId').notNull() })
export const account = pgTable('account', { id: text('id').primaryKey(), accountId: text('accountId').notNull(), providerId: text('providerId').notNull(), userId: text('userId').notNull(), accessToken: text('accessToken'), refreshToken: text('refreshToken'), idToken: text('idToken'), accessTokenExpiresAt: timestamp('accessTokenExpiresAt'), refreshTokenExpiresAt: timestamp('refreshTokenExpiresAt'), scope: text('scope'), password: text('password'), createdAt: timestamp('createdAt').notNull(), updatedAt: timestamp('updatedAt').notNull() })
export const verification = pgTable('verification', { id: text('id').primaryKey(), identifier: text('identifier').notNull(), value: text('value').notNull(), expiresAt: timestamp('expiresAt').notNull(), createdAt: timestamp('createdAt'), updatedAt: timestamp('updatedAt') })
export const workspaceMember = pgTable('workspace_member', { id: text('id').primaryKey(), userId: text('userId').notNull(), displayName: text('displayName').notNull(), role: text('role').notNull().default('member'), avatarColor: text('avatarColor').notNull().default('bg-violet-600'), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const sprint = pgTable('sprint', { id: text('id').primaryKey(), name: text('name').notNull(), goal: text('goal').notNull(), status: text('status').notNull().default('active'), startsAt: timestamp('startsAt').notNull(), endsAt: timestamp('endsAt').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const task = pgTable('task', { id: text('id').primaryKey(), key: text('key').notNull().unique(), title: text('title').notNull(), description: text('description').notNull().default(''), type: text('type').notNull().default('Task'), priority: text('priority').notNull().default('Medium'), status: text('status').notNull().default('To do'), dueDate: timestamp('dueDate'), project: text('project').notNull().default('Core Console'), area: text('area').notNull().default('Engineering'), points: integer('points').notNull().default(3), assigneeId: text('assigneeId').notNull(), reporterId: text('reporterId').notNull(), sprintId: text('sprintId'), blocked: boolean('blocked').notNull().default(false), createdAt: timestamp('createdAt').notNull().defaultNow(), updatedAt: timestamp('updatedAt').notNull().defaultNow() })
export const taskComment = pgTable('task_comment', { id: text('id').primaryKey(), taskId: text('taskId').notNull(), authorId: text('authorId').notNull(), body: text('body').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow() })
export const activity = pgTable('activity', { id: text('id').primaryKey(), actorId: text('actorId').notNull(), taskId: text('taskId'), action: text('action').notNull(), createdAt: timestamp('createdAt').notNull().defaultNow() })
